#!/usr/bin/env python3
"""Public path helpers for the ROBOTIS AI Worker example entrypoints.

These helpers intentionally avoid machine-local hardcoded paths. They resolve
URDFs from:

1. explicit ``--urdf`` / ``--collision-urdf`` CLI arguments,
2. a local clone of the public ``ROBOTIS-GIT/ai_worker`` repository, or
3. a cached download of that public repository.

Reduced collision assets generated by EmbodiK are bundled with the examples.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import tempfile
import urllib.request
import zipfile
from pathlib import Path

_AI_WORKER_REPO_GIT_URL = "https://github.com/ROBOTIS-GIT/ai_worker.git"
_AI_WORKER_REPO_ZIP_URL = "https://github.com/ROBOTIS-GIT/ai_worker/archive/refs/heads/main.zip"
_AI_WORKER_CACHE_DIR = Path(
    os.environ.get("EMBODIK_AI_WORKER_CACHE", "~/.cache/embodik/ai_worker")
).expanduser()

_PUBLIC_VARIANT_DIR_GLOBS = {
    "sg2": (
        "ffw_description/urdf/ffw_sg2*_follower/**/*.urdf",
        "ffw_description/urdf/**/*sg2*follower*.urdf",
    ),
    "bg2": (
        "ffw_description/urdf/ffw_bg2*_follower/**/*.urdf",
        "ffw_description/urdf/**/*bg2*follower*.urdf",
    ),
}


def _require_file(path: str | Path | None, label: str) -> Path | None:
    if path is None:
        return None
    resolved = Path(path).expanduser().resolve()
    if not resolved.is_file():
        raise FileNotFoundError(f"{label} does not exist: {resolved}")
    return resolved


def _candidate_public_roots(explicit_root: str | Path | None) -> list[Path]:
    roots: list[Path] = []
    if explicit_root:
        roots.append(Path(explicit_root).expanduser().resolve())
    for env_key in ("EMBODIK_AI_WORKER_ROOT", "AI_WORKER_ROOT"):
        env_value = os.environ.get(env_key, "").strip()
        if env_value:
            roots.append(Path(env_value).expanduser().resolve())
    unique_roots: list[Path] = []
    seen: set[Path] = set()
    for root in roots:
        resolved = root.expanduser().resolve()
        if resolved not in seen:
            seen.add(resolved)
            unique_roots.append(resolved)
    return unique_roots


def _resolve_from_public_repo(variant: str, ai_worker_root: str | Path | None) -> Path | None:
    variant = str(variant).strip().lower()
    for root in _candidate_public_roots(ai_worker_root):
        if not root.exists():
            continue
        for pattern in _PUBLIC_VARIANT_DIR_GLOBS.get(variant, ()):
            matches = sorted(root.glob(pattern))
            if matches:
                return matches[0].resolve()
    return None


def _download_public_repo_to_cache() -> Path:
    """Download the public ROBOTIS AI Worker repo into a stable user cache."""
    target = _AI_WORKER_CACHE_DIR / "ai_worker-main"
    if target.exists() and (target / "ffw_description").is_dir():
        return target

    _AI_WORKER_CACHE_DIR.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="embodik_ai_worker_") as tmp_name:
        tmp_dir = Path(tmp_name)
        extracted = tmp_dir / "ai_worker-main"
        git_path = shutil.which("git")
        if git_path:
            try:
                subprocess.run(
                    [
                        git_path,
                        "clone",
                        "--depth",
                        "1",
                        "--branch",
                        "main",
                        _AI_WORKER_REPO_GIT_URL,
                        str(extracted),
                    ],
                    check=True,
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.PIPE,
                    text=True,
                )
            except Exception:
                if extracted.exists():
                    shutil.rmtree(extracted)
        if not extracted.exists():
            zip_path = tmp_dir / "ai_worker-main.zip"
            try:
                urllib.request.urlretrieve(_AI_WORKER_REPO_ZIP_URL, zip_path)
            except Exception as exc:
                raise FileNotFoundError(
                    "Could not download the public ROBOTIS AI Worker assets from "
                    f"{_AI_WORKER_REPO_GIT_URL}. Provide --ai-worker-root, --urdf, "
                    "or set EMBODIK_AI_WORKER_ROOT to a local clone."
                ) from exc
            with zipfile.ZipFile(zip_path) as archive:
                archive.extractall(tmp_dir)
            extracted = tmp_dir / "ai_worker-main"
            if not extracted.exists():
                matches = sorted(path for path in tmp_dir.iterdir() if path.is_dir())
                if not matches:
                    raise FileNotFoundError(
                        "Downloaded AI Worker archive did not contain a repository directory."
                    )
                extracted = matches[0]
        staging = _AI_WORKER_CACHE_DIR / ".ai_worker-main.tmp"
        if staging.exists():
            shutil.rmtree(staging)
        shutil.move(str(extracted), str(staging))
        if target.exists():
            shutil.rmtree(target)
        staging.rename(target)
    return target


def _resolve_bundled_generated_urdf(variant: str) -> Path | None:
    examples_root = Path(__file__).resolve().parents[1]
    candidate = (
        examples_root
        / "assets"
        / "ai_worker"
        / "generated"
        / variant
        / f"ffw_{variant}_mobile_robot_teleop_collision.urdf"
    )
    return candidate.resolve() if candidate.is_file() else None


def resolve_public_ai_worker_urdf_paths(
    *,
    variant: str,
    ai_worker_root: str | Path | None = None,
    urdf: str | Path | None = None,
    collision_urdf: str | Path | None = None,
    allow_bundled_base_fallback: bool = True,
) -> tuple[Path, Path | None]:
    """Resolve the URDF inputs for the public AI Worker example."""
    variant = str(variant).strip().lower()
    if variant not in _PUBLIC_VARIANT_DIR_GLOBS:
        raise ValueError(f"Unsupported AI Worker variant '{variant}'. Expected one of: bg2, sg2")

    base_urdf = _require_file(urdf, "URDF")
    if base_urdf is None:
        base_urdf = _resolve_from_public_repo(variant, ai_worker_root)
    if base_urdf is None and allow_bundled_base_fallback:
        base_urdf = _resolve_bundled_generated_urdf(variant)
    if base_urdf is None:
        public_root = _download_public_repo_to_cache()
        base_urdf = _resolve_from_public_repo(variant, public_root)
    if base_urdf is None:
        raise FileNotFoundError(
            "Could not resolve an AI Worker URDF. Provide --urdf /path/to/model.urdf "
            "or --ai-worker-root /path/to/ROBOTIS-GIT/ai_worker."
        )

    collision_urdf_path = _require_file(collision_urdf, "Collision URDF")
    if collision_urdf_path is None:
        collision_urdf_path = _resolve_bundled_generated_urdf(variant)
    return base_urdf, collision_urdf_path
