"""Centralized constants for reachability visualization defaults."""

from __future__ import annotations

# Slider defaults
POINT_SIZE_SLIDER_MIN_CM = 0.5
POINT_SIZE_SLIDER_MAX_CM = 15.0
POINT_SIZE_SLIDER_STEP_CM = 0.25
POINT_SIZE_DEFAULT_CM = 1.0

MIN_SCORE_SLIDER_MIN = 0.0
MIN_SCORE_SLIDER_MAX = 1.0
MIN_SCORE_SLIDER_STEP = 0.01
MIN_SCORE_DEFAULT = 0.0

VISITATION_SCALE_MIN = 1.0
VISITATION_SCALE_MAX = 50.0
VISITATION_SCALE_STEP = 1.0
VISITATION_SCALE_DEFAULT = 10.0

Z_SLICE_MIN_M = -0.5
Z_SLICE_MAX_M = 2.5
Z_SLICE_STEP_M = 0.05
Z_SLICE_DEFAULT_M = 2.5

VALIDATION_SAMPLE_INDEX_DEFAULT = 0.0
VALIDATION_SAMPLE_INDEX_STEP = 1.0

# Visualization defaults
DEFAULT_BASE_COLOR = (0.9, 0.6, 0.2, 0.9)
DEFAULT_POINT_SIZE_M = 0.05
MIN_POINT_SIZE_M = 0.001
IK_DEBUG_TARGET_POINT_SCALE = 1.5
IK_DEBUG_TARGET_COLOR = (1.0, 0.95, 0.1, 1.0)  # yellowish

SAMPLE_PICKER_AXES_LENGTH_M = 0.0125
SAMPLE_PICKER_AXES_RADIUS_M = 0.001

# Color map tuning
GRADIENT_MIDPOINT = 0.5

# Orientation filter defaults
ORIENTATION_TOLERANCE_MIN_DEG = 5.0
ORIENTATION_TOLERANCE_MAX_DEG = 30.0
ORIENTATION_TOLERANCE_STEP_DEG = 1.0
ORIENTATION_TOLERANCE_DEFAULT_DEG = 15.0

# Metric computation constants
JOINT_LIMIT_EPSILON = 4e-2
DEFAULT_JOINT_LIMIT_DEADBAND_RATIO = 2.0 / 3.0
RANGE_OF_MOTION_NORMALIZED_LIMIT = 25.0
JOINT_LIMIT_DISTANCE_NORMALIZED_LIMIT = 25.0
NORMALIZATION_CACHE_DIRNAME = "metric_normalization"
NORMALIZATION_KEYS = (
    "RangeOfMotionRawMax",
    "SingularityWeightedMax",
    "SingularityRawMax",
)

# IK visualization / debugging defaults
IK_PROCESS_VISUALIZATION_DELAY_SEC = 0.05

# ============================================================================
# Reachability Map Column Indices
# ============================================================================

# FK reach_map tensor format (10 columns: xyz(3) + rpy(3) + visitation(1) + manip(1) + rom(1) + sing(1))
FK_REACH_MAP_XYZ_START = 0
FK_REACH_MAP_XYZ_END = 3
FK_REACH_MAP_RPY_START = 3
FK_REACH_MAP_RPY_END = 6
FK_REACH_MAP_VISITATION_COL = 6
FK_REACH_MAP_MANIP_COL = 7
FK_REACH_MAP_ROM_COL = 8
FK_REACH_MAP_SINGULARITY_COL = 9
FK_REACH_MAP_NUM_COLS = 10

# IK reach_map_rows format (14 columns: xyz(3) + rpy(3) + visitation(1) + manip(1) + rom(1) + sing(1) + quat(4))
IK_REACH_MAP_XYZ_START = 0
IK_REACH_MAP_XYZ_END = 3
IK_REACH_MAP_RPY_START = 3
IK_REACH_MAP_RPY_END = 6
IK_REACH_MAP_VISITATION_COL = 6
IK_REACH_MAP_MANIP_COL = 7
IK_REACH_MAP_ROM_COL = 8
IK_REACH_MAP_SINGULARITY_COL = 9
IK_REACH_MAP_QUAT_START = 10
IK_REACH_MAP_QUAT_END = 14
IK_REACH_MAP_NUM_COLS = 14

# Sphere dataset format (7 columns: xyz(3) + manip(1) + visitation(1) + rom(1) + sing(1))
# Used by both FK and IK maps in HDF5 files
SPHERE_DATASET_XYZ_START = 0
SPHERE_DATASET_XYZ_END = 3
SPHERE_DATASET_MANIP_COL = 3
SPHERE_DATASET_VISITATION_COL = 4
SPHERE_DATASET_ROM_COL = 5
SPHERE_DATASET_SINGULARITY_COL = 6
SPHERE_DATASET_NUM_COLS = 7

# FK sphere dataset old format (5 columns: xyz(3) + manip(1) + visitation(1))
SPHERE_DATASET_OLD_NUM_COLS = 5

# Minimum column counts for validation
SPHERE_DATASET_MIN_COLS = 5
SPHERE_DATASET_MIN_COLS_WITH_METRICS = 7
