name: CI

on:
  push:
    branches: [ main, packaging-and-docs ]
  pull_request:
    branches: [ main, packaging-and-docs ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0

      - name: Build and install package
        run: pixi run install

      - name: Run tests
        run: pixi run test
        continue-on-error: true

      - name: Check code formatting
        run: pixi run lint
        continue-on-error: true

  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0

      - name: Build and install package
        run: pixi run install

      - name: Build documentation
        run: pixi run python -W ignore::DeprecationWarning:hppfcl -m mkdocs build --strict
